### ISSUE TITLE
TeX公式问题

### ISSUE THREAD

**Issue by kyz20** [SivilTaram/Graph-Neural-Network-Note#2]
您好，我在你的博客上阅读出现了TeX公式显示不出的问题。刚点进页面时能正常显示公式，过了大概十秒有公式的地方就显示一片空白。我用的是最新的Chrome浏览器。
请问能否提供PDF版本? 十分感谢!

**Comment by SivilTaram** [comment]
@kyz20 你好，你可以把这个Repo下载到本地，然后用一些常用的MarkDown渲染器（据我所知VSCode+Markdown+Latex渲染插件就可以）就可以显示了
