### ISSUE TITLE
公式无法正常显示

### ISSUE THREAD

**Issue by kaiqiangh** [SivilTaram/Graph-Neural-Network-Note#4]
感谢分享，请问数学公式怎么能正常显示，谢谢~

**Comment by SivilTaram** [comment]
@kaiqiangh 可以移步我的博客阅读(cnblogs.com/SivilTaram)，或者可以在任意网页端MarkDown渲染器（如马克飞象等），将内容复制到其中即可渲染出Latex公式。

**Comment by kaiqiangh** [comment]
多谢！
